import assert from "node:assert/strict";
import { test } from "node:test";

import { classify, hasGeneratedHeader } from "../src/classify.ts";
import type { Class } from "../src/envelope.ts";
import { tempDir, writeFile } from "./helpers.ts";

test("classify sorts paths into classes", (t) => {
  const repo = tempDir(t);
  const cases: Array<[path: string, want: Class, generated: boolean]> = [
    ["src/store/user.ts", "source", false],
    ["src/components/Panel.tsx", "source", false],
    ["src/types/env.d.ts", "source", false],
    ["src/lib/worker.mts", "source", false],
    ["src/store/user.test.ts", "test", false],
    ["src/components/Panel.spec.tsx", "test", false],
    ["src/components/__tests__/Panel.tsx", "test", false],
    ["internal/store/user_test.go", "test", false],
    ["internal/store/testdata/golden.json", "test", false],
    ["vendor/example.com/dep/dep.go", "vendored", false],
    ["web/node_modules/react/index.js", "vendored", false],
    ["third_party/lib/lib.ts", "vendored", false],
    ["db/migrations/0001_users.sql", "migration", false],
    ["schema/000123_add_index.sql", "migration", false],
    ["src/1700000000000_add_users.ts", "migration", false],
    ["go.sum", "lockfile", true],
    ["web/package-lock.json", "lockfile", false],
    ["pnpm-lock.yaml", "lockfile", false],
    ["src/api/client.generated.ts", "generated", true],
    ["src/api/schema.gen.ts", "generated", true],
    ["src/api/Hooks.gen.tsx", "generated", true],
    ["api/user.pb.go", "generated", true],
    ["internal/oas_client.go", "generated", true],
    ["README.md", "other", false],
    ["src/index.js", "other", false],
  ];
  for (const [path, want, generated] of cases) {
    assert.deepEqual(classify(repo, { path, status: "M" }), [want, generated], path);
  }
});

test("hasGeneratedHeader reads only the header comments", (t) => {
  const repo = tempDir(t);
  const files: Record<string, [content: string, want: boolean]> = {
    "go-style.ts": ["// Code generated by openapi-gen. DO NOT EDIT.\n\nexport const x = 1;\n", true],
    "tagged.ts": ["/**\n * @generated\n */\nexport const x = 1;\n", true],
    "line-tag.ts": ["// @generated by relay-compiler\nexport const x = 1;\n", true],
    "openapi-typescript.ts": [
      "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\nexport interface paths {}\n",
      true,
    ],
    "openapi-generator.ts": [
      "/* tslint:disable */\n/* eslint-disable */\n/**\n * Petstore\n *\n * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).\n * Do not edit the class manually.\n */\nexport class Api {}\n",
      true,
    ],
    "shouting.ts": ["// THIS FILE IS AUTO-GENERATED, DO NOT MODIFY\nexport const x = 1;\n", true],
    "shebang.ts": ["#!/usr/bin/env node\n// Generated by scripts/gen.ts. Do not edit.\nexport {};\n", true],
    // The negative cases this classifier exists for: a hand-written file that
    // talks about the convention must stay reviewable.
    "discusses.ts": [
      `// A file whose header says "Code generated by X. DO NOT EDIT." is machine
// output, and this classifier must not hide this file because of that line.
export const marker = "Code generated by X. DO NOT EDIT.";
`,
      false,
    ],
    "mentions-in-body.ts": ["export function f() {}\n\n// @generated\nexport const x = 1;\n", false],
    "jsdoc-prose.ts": ["/**\n * Parses the generated client, which you should not edit by hand.\n */\nexport {};\n", false],
    "plain.ts": ["export const x = 1;\n", false],
    "deep.ts": ["//\n".repeat(40) + "// @generated\nexport {};\n", false],
  };
  for (const [name, [content]] of Object.entries(files)) {
    writeFile(repo, name, content);
  }
  for (const [name, [, want]] of Object.entries(files)) {
    assert.equal(hasGeneratedHeader(repo, name), want, name);
  }
});

test("classify does not read a deleted file's header", (t) => {
  const repo = tempDir(t);
  writeFile(repo, "src/client.ts", "// @generated\nexport {};\n");
  assert.deepEqual(classify(repo, { path: "src/client.ts", status: "M" }), ["generated", true]);
  // A deleted path is not in the working tree; the file on disk here stands in
  // for a stale one and must not be consulted.
  assert.deepEqual(classify(repo, { path: "src/client.ts", status: "D" }), ["source", false]);
});
