import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test, type TestContext } from "node:test";

import { validate, type Envelope } from "../src/envelope.ts";
import { fixtureRepo, git, runCli, tempDir, writeFile } from "./helpers.ts";

const pkgVersion = (JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8")) as { version: string })
  .version;

// changedFixture commits a small TypeScript project in a subdirectory and
// leaves a source edit, a regenerated client, and an untracked test behind.
function changedFixture(t: TestContext): string {
  const dir = fixtureRepo(t, {
    "web/tsconfig.json": "{}\n",
    "web/src/order.ts": "export function total(cents: number): number {\n  return cents;\n}\n",
    "web/src/client.ts": "// Code generated by openapi-gen. DO NOT EDIT.\n\nexport const url = '/v1';\n",
  });
  writeFile(
    dir,
    "web/src/order.ts",
    "export function total(cents: number): number {\n  if (cents < 0) {\n    return 0;\n  }\n  return cents;\n}\n",
  );
  writeFile(dir, "web/src/client.ts", "// Code generated by openapi-gen. DO NOT EDIT.\n\nexport const url = '/v2';\n");
  writeFile(dir, "web/src/order.test.ts", "import { total } from './order';\n\ntotal(1);\n");
  return dir;
}

test("context --changed --json emits a valid envelope with a classified manifest", (t) => {
  const dir = changedFixture(t);
  const res = runCli(["context", "--changed", "HEAD", "--json"], dir);
  assert.equal(res.status, 0, res.stderr);
  assert.equal(res.stderr, "");

  const env = JSON.parse(res.stdout) as Envelope;
  assert.equal(validate(env), undefined);
  assert.equal(env.schemaVersion, 1);
  assert.deepEqual(env.provider, { name: "tsrefactor", version: pkgVersion, language: "typescript" });
  assert.equal(env.baseSHA, git(dir, "rev-parse", "HEAD").trim());
  assert.deepEqual(env.files, [
    { path: "web/src/client.ts", class: "generated", generated: true },
    { path: "web/src/order.test.ts", class: "test" },
    { path: "web/src/order.ts", class: "source", symbols: ["total"] },
  ]);
  assert.equal(res.stdout, JSON.stringify(env, null, 2) + "\n");
});

test("--in selects the tree and paths stay relative to its top level", (t) => {
  const dir = changedFixture(t);
  const elsewhere = tempDir(t);
  const res = runCli(["context", "--changed=HEAD", "--in", `${dir}/web/src`, "--json"], elsewhere);
  assert.equal(res.status, 0, res.stderr);
  const env = JSON.parse(res.stdout) as Envelope;
  assert.deepEqual(
    env.files?.map((f) => f.path),
    ["web/src/client.ts", "web/src/order.test.ts", "web/src/order.ts"],
  );
});

test("context --changed without --json prints the human summary", (t) => {
  const dir = changedFixture(t);
  const res = runCli(["context", "--changed", "HEAD"], dir);
  assert.equal(res.status, 0, res.stderr);
  for (const want of [
    "context envelope v1",
    "provider tsrefactor",
    "files: 3 (generated 1, source 1, test 1)",
    "generated: 1 file(s) flagged",
    "symbols: 1",
    "expansions: 1 (enclosing 1)",
  ]) {
    assert.ok(res.stdout.includes(want), `summary missing ${JSON.stringify(want)}:\n${res.stdout}`);
  }
});

test("context argument rules are usage errors", (t) => {
  const dir = changedFixture(t);
  const cases: Array<[args: string[], firstLine: RegExp]> = [
    [["context"], /^context needs --changed <ref>$/],
    [["context", "--changed", "HEAD", "total"], /^context --changed takes no symbol argument \(got "total"\)$/],
    [["context", "--changed", "HEAD", "--budget", "500"], /^--budget does not apply to --changed; expansions are emitted whole/],
    [["context", "--changed", "HEAD", "--depth", "2"], /^unknown flag --depth$/],
    [["context", "--changed"], /^--changed needs a value$/],
    [["frobnicate"], /^unknown command: frobnicate$/],
    [[], /^usage: tsrefactor context --changed/],
  ];
  for (const [args, firstLine] of cases) {
    const res = runCli(args, dir);
    assert.equal(res.status, 1, args.join(" "));
    assert.equal(res.stdout, "", args.join(" "));
    assert.match(res.stderr.split("\n")[0]!, firstLine, args.join(" "));
  }
});

test("failures that abort the run explain themselves on the first stderr line", (t) => {
  const dir = changedFixture(t);
  const badRef = runCli(["context", "--changed", "no-such-ref", "--json"], dir);
  assert.equal(badRef.status, 1);
  assert.equal(badRef.stdout, "");
  assert.match(badRef.stderr.split("\n")[0]!, /^resolve the merge base with no-such-ref: git rev-parse/);

  const notRepo = tempDir(t);
  const outside = runCli(["context", "--changed", "HEAD", "--json"], notRepo);
  assert.equal(outside.status, 1);
  assert.match(outside.stderr.split("\n")[0]!, /^locate the work tree at \.: git rev-parse --show-toplevel: /);
});

test("version prints the package version", (t) => {
  const res = runCli(["--version"], tempDir(t));
  assert.equal(res.status, 0);
  assert.equal(res.stdout, pkgVersion + "\n");
});

// The property the consumer builds its evals on: the same revision produces
// the same bytes.
test("context --changed is deterministic", (t) => {
  const dir = changedFixture(t);
  const first = runCli(["context", "--changed", "HEAD", "--json"], dir);
  const second = runCli(["context", "--changed", "HEAD", "--json"], dir);
  assert.equal(first.status, 0, first.stderr);
  assert.equal(first.stdout, second.stdout);
});
