// File classification for the manifest. Ports gorefactor's
// internal/changectx/classify.go, with the generated-file conventions widened
// from Go's to the ones TypeScript codegen writes.

import { readFileSync } from "node:fs";
import { join, posix } from "node:path";

import type { Class } from "./envelope.ts";
import { isDeleted, type Change } from "./git.ts";

// headerScanLines bounds how far into a file a generated header is looked for.
const headerScanLines = 40;

// generatedMarkers are the header lines that mark machine output. Each one is
// anchored to the start of a comment's text: a substring test also matches a
// hand-written file that merely discusses the convention, and hiding a
// hand-written file from the reviewer is the one failure this classifier must
// never make.
const generatedMarkers = [
  // Go's convention, which some TypeScript generators also write.
  String.raw`code generated\b.*\bdo not edit\.?`,
  // The @generated tag, as a line comment or inside a JSDoc block.
  String.raw`@generated\b.*`,
  // "Generated by X. Do not edit.", "THIS FILE IS AUTO-GENERATED, DO NOT MODIFY".
  String.raw`(?:note:\s*)?(?:this (?:file|class|module|code) (?:is|was|has been) )?(?:auto[- ]?generated|automatically generated|generated)\b.*\bdo not (?:edit|modify|make (?:direct )?changes)\b.*`,
  // "This file was auto-generated by openapi-typescript.",
  // "NOTE: This class is auto generated by OpenAPI Generator".
  String.raw`(?:note:\s*)?this (?:file|class|module|code) (?:is|was|has been) (?:auto[- ]?generated|automatically generated|generated (?:automatically )?by)\b.*`,
];

const generatedHeaderRe = new RegExp(
  String.raw`^\s*(?:\/\/+|\/\*+|\*)?\s*(?:` + generatedMarkers.join("|") + String.raw`)\s*(?:\*\/)?\s*$`,
  "i",
);

// Naming conventions that mark output without a header. .d.ts is deliberately
// absent: declaration files in application repositories are nearly always
// hand-written ambient types, and they are exactly what a reviewer should read.
const generatedNameSuffixes = [
  ".generated.ts",
  ".generated.tsx",
  ".gen.ts",
  ".gen.tsx",
  ".pb.go",
  ".gen.go",
  "_string.go",
];
const generatedGoNamePrefixes = ["zz_generated.", "oas_"];
const generatedNames = new Set(["go.sum"]);

// lockfileNames are dependency lock files. They change constantly and carry no
// reviewable intent of their own.
const lockfileNames = new Set([
  "go.sum",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "Cargo.lock",
  "Gemfile.lock",
  "poetry.lock",
  "composer.lock",
]);

// migrationDirs are the directory names schema migrations conventionally live in.
const migrationDirs = new Set(["migrations", "migration", "migrate"]);

// migrationNameRe matches the numbered-prefix convention most migration tools
// write, such as 000123_add_users.up.sql or 1700000000000_add_users.ts.
const migrationNameRe = /^\d{3,}[_-].+\.(?:sql|go|ts|js)$/;

const testNameRe = /\.(?:test|spec)\.[cm]?[jt]sx?$/;
const sourceNameRe = /\.[cm]?tsx?$/;

// classify decides the manifest entry for one changed path. The order of the
// tests is the precedence: the first answer that applies wins, so a generated
// lock file reports as a lock file and still carries the generated flag.
export function classify(repo: string, c: Change): [Class, boolean] {
  const p = c.path.replaceAll("\\", "/");
  const base = posix.basename(p);
  const gen = isGeneratedName(base) || (!isDeleted(c) && hasGeneratedHeader(repo, p));

  if (hasSegment(p, "vendor") || hasSegment(p, "node_modules") || p.startsWith("third_party/")) {
    return ["vendored", gen];
  }
  if (lockfileNames.has(base)) {
    return ["lockfile", gen];
  }
  if (isMigration(p, base)) {
    return ["migration", gen];
  }
  if (gen) {
    return ["generated", true];
  }
  if (isTest(p, base)) {
    return ["test", gen];
  }
  if (sourceNameRe.test(base)) {
    return ["source", gen];
  }
  return ["other", gen];
}

function isGeneratedName(base: string): boolean {
  if (generatedNames.has(base)) {
    return true;
  }
  if (generatedNameSuffixes.some((s) => base.endsWith(s))) {
    return true;
  }
  return generatedGoNamePrefixes.some((p) => base.startsWith(p) && base.endsWith(".go"));
}

function isMigration(p: string, base: string): boolean {
  if (posix.dirname(p).split("/").some((seg) => migrationDirs.has(seg.toLowerCase()))) {
    return true;
  }
  return migrationNameRe.test(base);
}

// isTestPath reports whether a repo-relative path is test code.
export function isTestPath(p: string): boolean {
  return isTest(p, posix.basename(p));
}

function isTest(p: string, base: string): boolean {
  return (
    testNameRe.test(base) ||
    base.endsWith("_test.go") ||
    hasSegment(p, "__tests__") ||
    hasSegment(p, "testdata")
  );
}

function hasSegment(p: string, want: string): boolean {
  return p.split("/").includes(want);
}

// hasGeneratedHeader reports whether the file carries a generated marker above
// its first line of code. Reading stops at that first line, which is why a
// mention of the convention inside a function body cannot trigger it.
export function hasGeneratedHeader(repo: string, rel: string): boolean {
  let data: string;
  try {
    data = readFileSync(join(repo, rel), "utf8");
  } catch {
    return false;
  }
  let inBlock = false;
  for (const [i, line] of data.split("\n").entries()) {
    if (i >= headerScanLines) {
      return false;
    }
    const t = line.trim();
    if (t === "" || (i === 0 && t.startsWith("#!"))) {
      continue;
    }
    if (inBlock) {
      if (generatedHeaderRe.test(t)) {
        return true;
      }
      if (t.includes("*/")) {
        inBlock = false;
      }
    } else if (t.startsWith("/*")) {
      if (generatedHeaderRe.test(t)) {
        return true;
      }
      if (!t.slice(2).includes("*/")) {
        inBlock = true;
      }
    } else if (t.startsWith("//")) {
      if (generatedHeaderRe.test(t)) {
        return true;
      }
    } else {
      return false;
    }
  }
  return false;
}
